os: linux
language: python
python: 
    - "2.7"

cache: pip

services:
    - postgresql

install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - sudo apt update
    - ./scripts/psql_setup_linux

script:
    - travis_wait 20 pytest test

notifications:
    email:
        on_success: never
        on_failure: always
