os: linux
language: python
python: 
    - "2.7"

cache: pip

services:
    - postgresql

install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt
    - pip install codecov coverage pytest-cov
    - sudo apt update
    - ./scripts/psql_setup_linux

script:
    - pytest -s --cov=./ test
    - flake8 kaos
    - codecov

notifications:
    email:
        on_success: never
        on_failure: always
