os: linux
language: python
python: 
    - "2.7"

cache: pip

install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -r requirements.txt

script:
    - ./scripts/psql_setup_linux
    - pytest test

notifications:
    email:
        on_success: never
        on_failure: always
