"""This file contains routing code for the caching layer.

Author: Team KMC-70.
"""
import json

from flask import Blueprint, jsonify

from .errors import NotFoundError
from kaos.models import ResponseHistory

# pylint: disable=invalid-name
history_bp = Blueprint('history', __name__, url_prefix='/search')
# pylint: enable=invalid-name

@history_bp.route('/<int:history_id>', methods=['GET'])
def get_history(history_id):
    """Return the same response generated by a previous API call.

    Each API call should on success return a response with a UID. Querying this endpoint with this
    UID should generate the same response as was originally generated.

    Args:
        history_id (int): The UID of a previously successful response.
    """

    history = ResponseHistory.query.get(history_id)
    if history is None:
        raise NotFoundError("history_id", history_id)

    return jsonify(json.loads(history.response))

