#!/usr/bin/env bash

DATABASE_NAME="kaosdb"
DATABASE_USER="kaosuser"

alias psql_cmd="sudo -u postgres -i"

# Exit on first error
set -e

# Setup PSQL
sudo apt install postgresql postgresql-contrib

# Set up tables used by KAOS
psql_cmd createuser --interactive -P -s $DATABASE_USER
psql_cmd createdb $DATABASE_NAME

echo Created database: $DATABASE_NAME and user $DATABASE_USER please updated kaos/settings.py
